---

  - name: install mysql
    apt: name={{ item }} state=latest
    with_items:
      - mysql-server
      - mysql-client
      - python-mysqldb

  - name: add mysql user
    mysql_user: name=vagrant
                host={{ item }}
                password=vagrant priv=*.*:ALL,GRANT
                login_user=root
                login_password=
    with_items:
      - "{{ ansible_hostname }}"
      - 127.0.0.1
      - ::1
      - localhost

  - name: create mysql databases
    mysql_db: name={{ item }}
              state=present
    with_items:
      - monk

  - file: path=/etc/mysql/conf.d state=directory
